// <auto-generated />
using System;
using GraffitiClassificationApi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraffitiClassificationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531213432_SetStringColumnSizes")]
    partial class SetStringColumnSizes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Gang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("acronym");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("origin");

                    b.HasKey("Id");

                    b.ToTable("gangs", (string)null);
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Graffiti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GangId")
                        .HasColumnType("integer")
                        .HasColumnName("gang_id");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("ThreatLevel")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("threat_level");

                    b.Property<string>("VisualDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visual_description");

                    b.HasKey("Id");

                    b.HasIndex("GangId");

                    b.ToTable("graffitis", (string)null);
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.GraffitiLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<int>("GraffitiId")
                        .HasColumnType("integer")
                        .HasColumnName("graffiti_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.HasIndex("GraffitiId")
                        .IsUnique();

                    b.ToTable("graffitis_location", (string)null);
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Graffiti", b =>
                {
                    b.HasOne("GraffitiClassificationApi.Api.Models.Gang", "Gang")
                        .WithMany("Graffitis")
                        .HasForeignKey("GangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gang");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.GraffitiLocation", b =>
                {
                    b.HasOne("GraffitiClassificationApi.Api.Models.Graffiti", "Graffiti")
                        .WithOne("Location")
                        .HasForeignKey("GraffitiClassificationApi.Api.Models.GraffitiLocation", "GraffitiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graffiti");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Gang", b =>
                {
                    b.Navigation("Graffitis");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Graffiti", b =>
                {
                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
