// <auto-generated />
using System;
using GraffitiClassificationApi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraffitiClassificationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329184641_CaminhoImagem")]
    partial class CaminhoImagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Faccao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faccoes");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.LocalizacaoExata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("RegistroPichacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegistroPichacaoId")
                        .IsUnique();

                    b.ToTable("LocalizacoesExatas");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.RegistroPichacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoImagem")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoVisual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FaccaoId")
                        .HasColumnType("integer");

                    b.Property<string>("NivelAmeaca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FaccaoId");

                    b.ToTable("RegistrosPichacao");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.LocalizacaoExata", b =>
                {
                    b.HasOne("GraffitiClassificationApi.Api.Models.RegistroPichacao", "RegistroPichacao")
                        .WithOne("LocalizacaoExata")
                        .HasForeignKey("GraffitiClassificationApi.Api.Models.LocalizacaoExata", "RegistroPichacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPichacao");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.RegistroPichacao", b =>
                {
                    b.HasOne("GraffitiClassificationApi.Api.Models.Faccao", "Faccao")
                        .WithMany("RegistrosPichacao")
                        .HasForeignKey("FaccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faccao");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Faccao", b =>
                {
                    b.Navigation("RegistrosPichacao");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.RegistroPichacao", b =>
                {
                    b.Navigation("LocalizacaoExata");
                });
#pragma warning restore 612, 618
        }
    }
}
