// <auto-generated />
using System;
using GraffitiClassificationApi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraffitiClassificationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331234941_RenameTablesAndCollunsToSnakeCase")]
    partial class RenameTablesAndCollunsToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Faccao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Origem")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acronym");

                    b.HasKey("Id");

                    b.ToTable("gangs", (string)null);
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.LocalizacaoExata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<int>("RegistroPichacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("graffiti_id");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.HasIndex("RegistroPichacaoId")
                        .IsUnique();

                    b.ToTable("graffitis_location", (string)null);
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.RegistroPichacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoImagem")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("DescricaoVisual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visual_description");

                    b.Property<int>("FaccaoId")
                        .HasColumnType("integer")
                        .HasColumnName("gang_id");

                    b.Property<string>("NivelAmeaca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("threat_level");

                    b.HasKey("Id");

                    b.HasIndex("FaccaoId");

                    b.ToTable("graffitis", (string)null);
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.LocalizacaoExata", b =>
                {
                    b.HasOne("GraffitiClassificationApi.Api.Models.RegistroPichacao", "RegistroPichacao")
                        .WithOne("LocalizacaoExata")
                        .HasForeignKey("GraffitiClassificationApi.Api.Models.LocalizacaoExata", "RegistroPichacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroPichacao");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.RegistroPichacao", b =>
                {
                    b.HasOne("GraffitiClassificationApi.Api.Models.Faccao", "Faccao")
                        .WithMany("RegistrosPichacao")
                        .HasForeignKey("FaccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faccao");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.Faccao", b =>
                {
                    b.Navigation("RegistrosPichacao");
                });

            modelBuilder.Entity("GraffitiClassificationApi.Api.Models.RegistroPichacao", b =>
                {
                    b.Navigation("LocalizacaoExata");
                });
#pragma warning restore 612, 618
        }
    }
}
